[editors]
emacs = false
helix = false
neovim = true
vscode = true
zed = false

[profiles]
developer = true
gaming = false
server = false
work = false

[shells]
zsh = true
fish = true
nushell = false

[toolchains]
ai = false
cc = true
hoon = false
golang = false
javascript = false
python = true
ruby = false
rust = false
shell = false
