[".local/share/asdf"]
type = "git-repo"
url = "https://github.com/asdf-vm/asdf.git"
exact = true
refreshPeriod = "48h"

{{ if eq .editor "emacs" -}}
[".config/emacs"]
type = "git-repo"
url = "https://github.com/doomemacs/doomemacs.git"
exact = true
refreshPeriod = "24h"
{{ end -}}
