[packages.darwin]
taps = ["homebrew/cask-fonts"]
brews = [
    "bat",
    "cmake",
    "coreutils",
    "dockutil",
    "duti",
    "eza",
    "fd",
    "fish",
    "fzf",
    "git",
    "jq",
    "mas",
    "ripgrep",
    "shellcheck",
    "sqlite3",
    "task",
    "tealdeer",
    "xz",
]
casks = ["appcleaner", "iina", "iterm2@beta", "secretive"]
apps = []
fonts = ["font-ibm-plex-mono", "font-jetbrains-mono-nerd-font"]
gamingApps = [
  "steam", "gog-galaxy", "whisky"
]
